services:
  server:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: ["python", "/app/entrypoint.py"]
    command: ["/bin/bash", "start_app.sh"]
